# -*- coding: utf-8 -*-
"""DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTmzxKfNISp74xVqgpRvVXfsSjHYLY4i
"""

import pandas as pd

# creating simple table usig dataframe
student_info= {
    "Name"  : ["nikita","priya","aarti","vedika"],
    "City" : ["pune","mumbai","nagpur","delhi"],
    "CGPA" :[7.6,8.4,7.2,9.5],
    "Age" : [21,22,23,24]

}
data=pd.DataFrame(student_info)
print(data)

print(data["Name"])

print(data.columns)

# creating DataFrame using numpy
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
df=pd.DataFrame(arr,columns=['a','b','c'])
print(df)

# Load csv file as a df
df=pd.read_csv("/content/raw_data.csv")
print(df)

print(df.head()) # show 1st 5 rows

print(df.tail()) # show last 5 rows

print(df.columns) # show column names

print(df.info()) # show summary of data

print(df.shape) # show total row.total column

print(df.describe()) # show mathematical terms for only numerical column

# show specific range of column
print(df.loc[0:3])  # start : end->(inclusinve)
print(df.iloc[0:3])    # start : end->(exclusinve)