# -*- coding: utf-8 -*-
"""series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcKtseUlaYuL5-vgrL5ybJxwgobmOb5z
"""

# importing pandas library
import pandas as pd

# series using pandas with same data type elements
s=pd.Series([10,20,30,40,50])
print(s)

# convert all elements data type to float
# int -> float
s=pd.Series([10,2.5,30,4.4,50])
print(s)

# convert all elements data type to object
# int -> float -> string -> object
s=pd.Series([32,4.2,13,"abc",50])
print(s)

# custom index  named
s=pd.Series([32,41,20,45],index=['nikita','aarti','priya','aaru'])
print(s)

# creating series using list
list=[11,22,33,44,55]
s=pd.Series(list)
print(s)

# creating series using numpy
import numpy as np
arr=np.array([11,22,33,44,55])
s=pd.Series(arr,index=['a','b','c','d','e'])
print(s)

data=pd.Series({'a':10,'b':20,'c':30})
print(data)
print(data.index)