# -*- coding: utf-8 -*-
"""Data_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w49W-2gUpz2-XC0hJLphefPcgyYEvH1d
"""

import pandas as pd

data=pd.read_csv("/content/raw_data.csv")
data

data["income"].hist()

data.plot(kind="scatter",x="income",y="age")