# -*- coding: utf-8 -*-
"""Transforming_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-ixVBci4kPsE5VtEZOr3zl1zbXUhfa0
"""

import pandas as pd

data=pd.read_csv("/content/sample_data.csv")
data

"""Transforming Data

Feature Engineering
"""

# 1) apply(function) = apply condition on each element
# used with dataframe and series
data["Result"]= data["Score"].apply(lambda x :"Pass" if x>=70 else "Fail")
data

# 2) map(function) =replace or transform the values
# used with only series
data["Result"]=data["Result"].map({"Pass":"P","Fail":"F"})
data

# 3) assign()
data.assign(new_score=lambda x: data["Score"]+ 5)

# 4) replace("old","new")
data.replace("Aurangabad","Nandurabar")

data.rename(columns={"Score":"Marks"})

data2=data.copy()
data2.sort_values(by="Score")

"""Groupby function with Aggregate function

"""

data.groupby("Name")["Score"].mean()

data.groupby("City")["Score"].count()

"""Groupby with multiple Aggregate fun"""

data.groupby("City")["Score"].agg(["mean","count","sum","max"])