# -*- coding: utf-8 -*-
"""numpy_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzO6tD2p5XvJaFsYZZvSv6D3QQPGCyAC
"""

# importing numpy
import numpy as np

# creating the array
arr=np.array([[1,2,3],[4,5,6]])

# array properties
print(arr )
print(arr.shape )
print(arr.size )
print(arr.ndim )
print(arr.dtype )
print(arr.reshape(3,2))

# array methods
print(np.zeros((4,2)))
print(np.ones((4,2)))
print(np.full((4,2),5))
print(np.eye(3))
print(np.arange(0,55,5))
print(np.linspace(4,10,5))

# list slicing
list=[1,3,4,5,6]
print(list[:3])

# array slicing
arr=np.array([1,2,3,4,5,6])
print(arr[1:4])

# arithmetic operations on 2D array
arr=np.array([[1,2],[3,4]])
arr1=np.array([[5,6],[7,8]])
print(arr + arr1)
print(arr - arr1)
print(arr * arr1)
print(arr / arr1)
print(arr % arr1)