# -*- coding: utf-8 -*-
"""Data_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LCabGvF8WQKA_JsAX1hTeNpQZN6bDGN7
"""

import pandas as pd

data= pd.read_csv("/content/raw_data.csv")
data

"""**Handle Missing values using various methods**"""

# 1) isnull() = check null values in data
# True = null value
print(data.isnull())

# 2) isnull().sum()
# count null values per column
print(data.isnull().sum())

# 3)fillna(value)
# fill all null values by default value
print(data.fillna(0))

# 4)ffill()  = forward filling
# fill the cell with his upper cell value
print(data.ffill())

# 5)bfill()  = backward filling
# bill the cell with his lower cell value
print(data.bfill())

# 6) dropna()
# drop the row that have null values
print(data.dropna())

# 7) dropna(axis=1)
# drop the column that have null value
print(data.dropna(axis=1))

# 8)diplicated()
print(data.duplicated())

# 9) drop_duplicates()
print(data.drop_duplicates())

data

# show datatype per columns values
data.dtypes