# -*- coding: utf-8 -*-
"""Filtering data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tsoDQJ-UzsEpr6Whp1szuYt0v954DdY
"""

import pandas as pd

data=pd.read_csv("/content/raw_data.csv")
data.head()

""" Indexing and Slicing"""

# show full record of row at 2nd index
print(data.loc[2])

# show 1st and 5th column values in range 0 -> 2
print(data.loc[0:2,["name","income"]])

# using iloc -> allow only index value of column
# ending index is not include in range

# show full record of row at 2nd index
print(data.iloc[2])

# show 1st and 5th column values in range 0->1
print(data.iloc[0:2,[1,5]])

"""**Apply condition on data**"""

# print all data which fullfill this condition
print(data[(data["age"]>20)& (data["gender"]=="Female")])

# print name and income data which fullfill  this condition
print(data[(data["age"]>20)& (data["gender"]=="Female")] [["name","income"]])

# using Ouery method
print (data.query("age>30 & gender=='Male'"))

# using query method with specific columns
print (data.query("country=='USA' & income>50000")[["name","age"]])

"""operations on string data"""

# 1) str.upper() = convert all string in upper letters
print(data["name"].str.upper())

# 2) str.lower() = convert all string in lower letters
print(data["name"].str.lower())

# 3) str.capitalize() = convert all string in capilize format
print(data["country"].str.capitalize())

# 4) str.contains("value") = check value is present or not
# True = present
print(data["country"].str.contains("India"))

# if value if present but not detect then use case=False (not case sensitive)
print(data["country"].str.contains("usa",case=False))